### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by nk932714** [kaioduarte/torrent-extractor#1]

**Comment by kaioduarte** [comment]
@nk932714 could you post these links that are not working?

**Comment by nk932714** [comment]
example :-  https://www.freetutorials.us/wp-content/uploads/2018/08/FreeTutorials.Us-dc-level-2.torrent

**Comment by kaioduarte** [comment]
@nk932714 this tool not work as you thought. It is not intended to extract `torrent file info`, instead it is intended to extract `magnet links` from sites that have a lot of ads or fake URLs like [this one](http://www.filmesviatorrents.org/torrent-vingadores-guerra-infinita-download-bluray-720p-1080p-dublado-dual-audio-2018).

**Comment by nk932714** [comment]
ok thanks buddy @kaioduarte
